# Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://13.209.16.121:3306/luti
spring.datasource.username=root
spring.datasource.password=hwangkh704!

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update